var piadas = [
    "Por que os cintos foram presos? Porque eles seguravam as calças!",
    "O que o zero disse para o oito? Belo cinto!",
    "O que o tomate foi fazer no banco? Tirar extrato.",
    "Qual é a tecla preferida do astronauta? A barra de espaço.",
    "Por que os fantasmas são péssimos para contar mentiras? Porque são transparentes.",
    "Ouviu falar sobre o novo restaurante chamado Karma? Não tem cardápio: você recebe o que merece.",
    "Você ouviu falar sobre o astronauta claustrofóbico? Ele só precisava de um pouco de espaço.",
    "O que o olho esquerdo disse para o olho direito? Entre você e eu, algo cheira.",
    "Por que o jogador de futebol demorou tanto para jantar? Porque ele achava que não podia usar as mãos.",
    "Nomeie o tipo de árvore que você pode segurar em sua mão? Uma palmeira!",
    "Por que as aves voam para o sul no inverno? É mais rápido do que caminhar!",
    "A mãe de Sandy tem quatro filhos; Norte, Oeste, Leste. Qual o nome do quarto filho? Sandy, obviamente!",
    "O que é castanho, peludo e usa óculos escuros? Um coco de férias.",
    "O que um livro de matemática dizia ao outro? “Tenho tantos problemas.",
    "Qual planeta gosta de cantar? Nep-tune!",
    "Por que o menino estava falando ao telefone deitado? Para não cair a ligação.",
    "Todas as frutas foram passar as férias na montanha, menos o mamão. Porque o mamão foi papaia!",
    "Por que a mulher do Hulk se divorciou dele? Porque ela queria um homem mais maduro.",
    "Por que as plantinhas não falam? Porque elas são mudas.",
    "Quer ouvir uma piada de construção? Ah, não importa, eu ainda estou trabalhando nisso.",
    "Por que os franceses comem caracóis? Eles não gostam de fast food.",
    "Sabe o que eu vi hoje? Tudo o que eu olhava.",
    "O que o homem disse aos dedos? Conto com vocês.",
    "Por que a Coca-Cola e a Fanta se dão muito bem? Porque se a Fanta quebrar, a Coca-Cola.",
    "Você conhece a piada do fotógrafo? Ainda não foi revelada.",
    "Para que serve o óculos verde? Para verde perto.",
    "Sabe como é a piada do pintinho caipira? Pir.",
    "Por que o pinheiro não se perde na floresta? É porque ele tem uma pinha",
    "Você sabe quem é o rei dos queijos? É o reiqueijão.",
    "Batman pegou seu bat-sapato social e seu bat-blazer. Aonde ele foi? A um Bat-zado.",
    "Como o Batman faz para que abram a bat-caverna? Ele bat-palma.",
    "Para que serve óculos vermelho? Para vermelhor.",
    "Por que o bombeiro não gosta de andar? Porque ele socorre!",
    "Qual é o nome do carro que mostra que vai chover? Celta preto!",
    "O que o alienígena foi fazer em São Paulo? Foi visitar o Tioetê!",
    "Qual é o queijo que mais sofre? O queijo ralado!",
    "Qual remédio avisa quando você está bebendo demais? O paracetamal!",
    "Qual a cidade brasileira que não tem taxi? Uberlândia!",
    "Por que o rádio não pode ter filhos? Porque ele é estéreo.",
    "O que um cromossomo falou para o outro? Cromossomos bonitos!",
    "Qual é a galinha que cai no chão e surta? A galinha cai i pira.",
    "O que o advogado do frango foi fazer na delegacia? Foi soltar a franga!",
    "Que raça de gato pula mais alto que um prédio? Qualquer uma, porque prédio não pula.",
    "Por que as estrelas não podem ser gatos? Porque astro não mia.",
    "Sabe por que o rapaz jogou o computador no mar? Para ele navegar na internet!",
    "Por que os elétrons nunca são convidados para festas? Porque eles são muito negativos.",
    "Qual foi a primeira vez que os americanos comeram carne? Quando chegou Cristóvão Com Lombo.",
    "O que é uma mulher velha sem relógio? Uma Sem Hora.",
    "Sabe porque o policial não gosta de sabão em pó? Porque ele gosta de deter-gente.",
    "O que é um piolho na cabeça de um careca? Um sem terra.",
    "Porque a Julia só tem chulé no pé esquerdo? Porque quando pequena, a mãe dela falava: “Lava esse pé direito, Julia!”",
    "Qual a diferença entre a pizza e a sua opinião? É que a pizza eu pedi.",
    "Todas as frutas foram tirar férias nas montanhas, menos o mamão. Sabe porquê? Porque o mamão foi papaia.",
    "A plantinha foi à emergência do hospital, mas não conseguiu ser atendida, por quê? Porque lá só tinha médico de plantão.",
    "Você conhece o site do cavalinho? É www ponto cavalinho ponto com ponto com ponto com ponto com.",
    "O que o pagodeiro foi fazer na igreja? Foi cantar Pá God.",
    "O que é, o que é: Maconha enrolada em jornal? Baseado em fatos reais.",
    "2 litros de leite atravessaram a rua e foram atropelados. Um morreu, o outro não, por quê? Porque um deles era longa vida.",
    "Por que o elefante não pega fogo? Porque ele já é cinza.",
    "Como as enzimas se reproduzem? Fica uma enzima da outra.",
    "Por que o jacaré tirou o jacarezinho da escola? Porque ele réptil de ano.",
    "Que nome se dá a uma ferramenta perdida? Foice.",
    "Qual é o alimento mais sagrado que existe? O amém doim.",
    "Por que o rádio não pode ter filhos? Porque ele é stereo.",
    "O que é um astrólogo andando a cavalo? Um Cavaleiro do Zodíaco.",
    "Por que os ovos não contam piadas? Porque eles iam rachar de tanto rir.",
    "Por que a vaca foi para o espaço? Para se encontrar com o vácuo.",
    "O que fala o livro de Matemática para o livro de História? Não me venha com história que eu já estou cheio de problema!",
    "O que os elfos aprendem na escola? O Elf-abeto.",
    "Por que fantasmas são péssimos mentirosos? Porque você pode ver através deles.",
    "Por que o rei foi ao banheiro? Ele queria sentar no trono!",
    "Por que Napoleão era sempre chamado para as festas na França? É porque ele era Bom Na Party.",
    "Por que a aranha é o animal mais carente do mundo? Porque ela é um aracneedyou.",
    "— O meu filho completou dois anos ontem e já está andando há seis meses. — Nossa! Ele já deve estar bem longe.",
    "— Leila, você quer ir na minha festa de quinze anos? Claro! Mas só vou poder ficar algumas horas.",
    "Um caipira chega à casa de um amigo que estava vendo TV e pergunta: – E aí, firme? O outro responde: – Não, futebor!",
    "Qual é a parte favorita de um astronauta em um computador? A tecla de espaço.",
    "Eu tenho uma piada sobre química. Mas não acho que vai ter uma reação.",
    "O que fica mais úmido quanto mais seca? Uma toalha.",
    "O que um vulcão perguntou ao outro ao acordarem? Você se lava?",
    "Como você chama o homem que passa roupas? Homem de Ferro.",
    "Por que o pão não entende a batata? Porque o pão é francês e a batata é inglesa.",
    "Qual é o tio da construção? O Tio Jolo.",
    "Por que a fração estava nervosa em se casar com o decimal? Porque ela teria que se converter.",
    "Por que o computador estava com frio? Ele tinha um vírus.",
    "Era uma vez um pintinho que se chama Relam. Toda vez que chovia, Relam piava!",
    "O que o tijolo falou para o outro? Há um ciumento entre nós.",
    "Qual a fruta que anda de trem? O kiwiii.",
    "O que é um pontinho preto no avião? Uma aeromosca.",
    "Como que o mineiro usa a internet? Pelo UAI-fai",
    "Qual é o melhor tratamento para pessoas que sofrem de queda constante? Para-quedismo.",
    "Um tênis foi jogado ao mar e afundou. Qual o nome do filme? Titanike.",
    "O que um álcool disse para outro álcool? Etanois!",
    "Qual o contrário de papelada? Pá vestida.",
    "O que o cadarço falou para o tênis? Eu me amarro em você.",
    "Como o Batman conheceu o Robin? Pelo bat-papo.",
    "Por que o porco está sempre feliz? Porque está de bacon a vida.",
    "Qual é o cúmulo da solidão? Morar sozinho e fugir de casa.",
    "Por que o cachorro entrou na igreja? Porque é um pastor alemão."
];
var piadaAtual = document.getElementById("piada");
var feedback = document.getElementById("feedback");
// Função para gerar aletoriamente as piadas
function gerarPiada() {
    var indice = Math.floor(Math.random() * piadas.length);
    piadaAtual.textContent = piadas[indice];
}
// mensagem do gostei
function gostei() {
    feedback.textContent = "Obrigado pelo seu feedback positivo, um excelente dia!";
    gerarPiada();
}
// mensagem de não gostei
function naoGostei() {
    feedback.textContent = "Infelizmente sua piada não foi boa o suficiente";
    gerarPiada();
}
// Gerando
gerarPiada();
